<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/teachisspam/localization/<lang>.inc                            |
 |                                                                       |
 | Localization file of the Roundcube Webmail Mark-As-Junk plugin        |
 | Copyright (C) 2012-2013, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 
*/
$labels['buttontext'] = 'Отпад';
$labels['buttontitle'] = 'Означи као отпад';
$labels['reportedasjunk'] = 'Успешно пријављено као отпад';
?>